name: Deploy

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:

  web:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write
    environment:
      name: ${{ github.ref == 'refs/heads/main' && 'iwcapital' || '' }}
      url: https://jewl.app/
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
      - name: Install Dependencies
        run: npm ci
      - name: Build Web
        run: npm run build web
      - name: Bundle Web
        run:  npx parcel build --no-cache --no-autoinstall
      - name: Deploy Web
        if: ${{ !github.event.pull_request.head.repo.fork }}
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_DEPLOY_KEY }}
          channelId: ${{ github.ref == 'refs/heads/main' && 'live' || '' }}
          expires: ${{ github.ref == 'refs/heads/main' && '' || '3d' }}
          projectId: iwcapital
